"""update pokemon hp

Revision ID: d805ab5742eb
Revises: c2220c69eb68
Create Date: 2026-06-29 08:36:42.119513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd805ab5742eb'
down_revision = 'c2220c69eb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.alter_column('types',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.alter_column('types',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=False)

    # ### end Alembic commands ###
